# Generated by Django 5.2.17 on 2026-08-30 17:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Startup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('full_name', models.CharField(max_length=150, verbose_name='F.I.O.')),
                ('phone', models.CharField(max_length=25, verbose_name='Telefon raqami')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('region', models.CharField(choices=[('toshkent_shahri', 'Toshkent shahri'), ('toshkent', 'Toshkent viloyati'), ('samarqand', 'Samarqand viloyati'), ('buxoro', 'Buxoro viloyati'), ('navoiy', 'Navoiy viloyati'), ('qashqadaryo', 'Qashqadaryo viloyati'), ('surxondaryo', 'Surxondaryo viloyati'), ('fargona', "Farg'ona viloyati"), ('andijon', 'Andijon viloyati'), ('namangan', 'Namangan viloyati'), ('xorazm', 'Xorazm viloyati'), ('sirdaryo', 'Sirdaryo viloyati'), ('jizzax', 'Jizzax viloyati'), ('qoraqalpogiston', "Qoraqalpog'iston Respublikasi")], max_length=30, verbose_name='Viloyat')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Tuman / shahar')),
                ('name', models.CharField(max_length=200, verbose_name='StartUp nomi')),
                ('sphere', models.CharField(choices=[('it', "IT / Dasturiy ta'minot"), ('fintech', 'Fintech'), ('edtech', "EdTech — ta'lim"), ('agrotech', "AgroTech — qishloq xo'jaligi"), ('medtech', 'MedTech — tibbiyot'), ('ecommerce', 'E-commerce / Savdo'), ('logistics', 'Logistika'), ('green', 'Ekologiya va yashil energiya'), ('media', 'Media va kontent'), ('other', 'Boshqa')], max_length=20, verbose_name="Yo'nalish")),
                ('stage', models.CharField(choices=[('idea', "G'oya bosqichi"), ('mvp', 'MVP tayyor'), ('launched', 'Bozorga chiqqan'), ('scaling', 'Kengaytirilmoqda')], default='idea', max_length=20, verbose_name='Bosqich')),
                ('about', models.TextField(verbose_name='StartUp haqida')),
                ('problem_solved', models.TextField(blank=True, verbose_name='Qanday muammoni hal qiladi')),
                ('team_size', models.PositiveIntegerField(default=1, verbose_name="Jamoa a'zolari soni")),
                ('needed_investment', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name="Kerakli investitsiya (so'm)")),
                ('pitch_file', models.FileField(blank=True, upload_to='startups/pitch/%Y/%m/', verbose_name='Pitch fayl')),
                ('logo', models.ImageField(blank=True, upload_to='startups/logos/%Y/%m/', verbose_name='Logotip')),
                ('website', models.URLField(blank=True, verbose_name='Veb-sayt')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('review', "Ko'rib chiqilmoqda"), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('done', 'Bajarilgan')], default='pending', max_length=20, verbose_name='Holat')),
                ('admin_note', models.TextField(blank=True, verbose_name='Admin izohi')),
                ('is_public', models.BooleanField(default=True, verbose_name="Ommaviy ro'yxatda ko'rinsin")),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='startups', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'StartUp',
                'verbose_name_plural': 'StartUplar',
                'ordering': ['-created_at'],
            },
        ),
    ]
