# Generated by Django 5.2.17 on 2026-09-16 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='startup',
            index=models.Index(fields=['is_public', 'status', '-created_at'], name='startups_st_is_publ_664880_idx'),
        ),
    ]
