# Generated by Django 5.2.17 on 2026-09-30 06:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0002_tezlik_indekslari'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InvestmentOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('full_name', models.CharField(max_length=150, verbose_name='F.I.O.')),
                ('phone', models.CharField(max_length=25, verbose_name='Telefon')),
                ('telegram', models.CharField(blank=True, max_length=64, verbose_name='Telegram')),
                ('status', models.CharField(choices=[('new', 'Yangi'), ('accepted', 'Qabul qilingan'), ('declined', 'Rad etilgan')], default='new', max_length=20, verbose_name='Holat')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Javob berilgan')),
                ('outcome', models.CharField(blank=True, choices=[('deal', 'Kelishdik'), ('talking', 'Muzokara davom etmoqda'), ('no_deal', 'Kelishmadik')], max_length=20, verbose_name='Natija')),
                ('feedback', models.TextField(blank=True, verbose_name='Fikr')),
                ('feedback_at', models.DateTimeField(blank=True, null=True, verbose_name='Fikr bildirilgan')),
                ('feedback_ask_after', models.DateTimeField(blank=True, null=True, verbose_name="Fikr so'rash vaqti")),
                ('investor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='investment_offers', to=settings.AUTH_USER_MODEL, verbose_name='Investor')),
                ('startup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='startups.startup', verbose_name='Startap')),
            ],
            options={
                'verbose_name': 'Investitsiya taklifi',
                'verbose_name_plural': 'Investitsiya takliflari',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='startups_in_status_0fc0a4_idx')],
                'constraints': [models.UniqueConstraint(fields=('startup', 'investor'), name='bir_startapga_bitta_taklif')],
            },
        ),
    ]
