# Generated by Django 5.2.17 on 2026-10-10 09:48

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('startups', '0003_investitsiya_takliflari'),
    ]

    operations = [
        migrations.CreateModel(
            name='OfficeStartup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('full_name', models.CharField(max_length=150, verbose_name='Asoschi F.I.Sh.')),
                ('district', models.CharField(blank=True, max_length=40, verbose_name='Tuman / shahar')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('age', models.PositiveSmallIntegerField(blank=True, help_text="Tug'ilgan sana noma'lum bo'lsa", null=True, verbose_name='Yoshi')),
                ('photo', models.ImageField(blank=True, upload_to='ofis/asoschilar/%Y/%m/', verbose_name='Asoschi rasmi')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='Telefon')),
                ('telegram', models.CharField(blank=True, max_length=64, verbose_name='Telegram username')),
                ('name', models.CharField(max_length=200, verbose_name='Loyiha nomi')),
                ('about', models.TextField(blank=True, verbose_name='Loyiha haqida')),
                ('sphere', models.CharField(choices=[('edtech', "EdTech — ta'lim texnologiyalari"), ('greentech', 'GreenTech — ekologiya va energiya tejash'), ('ai', "AI & Data — sun'iy intellekt va tahlil"), ('healthtech', 'HealthTech — tibbiyot innovatsiyalari'), ('social', 'Social Impact — ijtimoiy muammolar yechimi'), ('fintech', 'FinTech — raqamli moliyaviy xizmatlar'), ('agritech', "AgriTech — aqlli qishloq xo'jaligi"), ('ecommerce', 'E-commerce — onlayn savdo'), ('logistics', 'Logistics — transport va yetkazib berish'), ('smartcity', 'Smart City — aqlli shahar'), ('tourism', 'Turizm'), ('other', 'Boshqa')], db_index=True, default='other', max_length=20, verbose_name='Soha')),
                ('stage', models.CharField(choices=[('idea', "G'oya"), ('mvp', 'MVP'), ('sales', 'Sotuv'), ('seed', 'Seed')], db_index=True, default='idea', max_length=20, verbose_name='Bosqich')),
                ('project_image', models.ImageField(blank=True, upload_to='ofis/loyihalar/%Y/%m/', verbose_name='Loyiha rasmi')),
                ('is_published', models.BooleanField(default=True, verbose_name="Saytda ko'rinadi")),
                ('import_key', models.CharField(blank=True, db_index=True, editable=False, max_length=64)),
            ],
            options={
                'verbose_name': 'Ofis startapi',
                'verbose_name_plural': 'Samarqand startuplar ofisi',
                'ordering': ['-created_at', '-id'],
                'indexes': [models.Index(fields=['is_published', '-created_at'], name='startups_of_is_publ_41c0d8_idx')],
            },
        ),
    ]
