# Generated by Django 5.2.17 on 2026-08-30 17:27

import apps.accounts.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Email')),
                ('full_name', models.CharField(max_length=150, verbose_name='F.I.O.')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='Telefon')),
                ('role', models.CharField(choices=[('entrepreneur', 'Tadbirkor'), ('startupper', 'Startupper'), ('organization', 'Tashkilot'), ('admin', 'Administrator')], default='entrepreneur', max_length=20, verbose_name='Rol')),
                ('region', models.CharField(blank=True, choices=[('toshkent_shahri', 'Toshkent shahri'), ('toshkent', 'Toshkent viloyati'), ('samarqand', 'Samarqand viloyati'), ('buxoro', 'Buxoro viloyati'), ('navoiy', 'Navoiy viloyati'), ('qashqadaryo', 'Qashqadaryo viloyati'), ('surxondaryo', 'Surxondaryo viloyati'), ('fargona', "Farg'ona viloyati"), ('andijon', 'Andijon viloyati'), ('namangan', 'Namangan viloyati'), ('xorazm', 'Xorazm viloyati'), ('sirdaryo', 'Sirdaryo viloyati'), ('jizzax', 'Jizzax viloyati'), ('qoraqalpogiston', "Qoraqalpog'iston Respublikasi")], max_length=30, verbose_name='Viloyat')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Tuman / shahar')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name="Tug'ilgan sana")),
                ('avatar', models.ImageField(blank=True, upload_to='avatars/%Y/%m/', verbose_name='Rasm')),
                ('bio', models.TextField(blank=True, verbose_name="O'zi haqida")),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Xodim')),
                ('is_verified', models.BooleanField(default=False, verbose_name='Tasdiqlangan')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Ro'yxatdan o'tgan")),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': 'Foydalanuvchi',
                'verbose_name_plural': 'Foydalanuvchilar',
                'ordering': ['-date_joined'],
            },
            managers=[
                ('objects', apps.accounts.models.UserManager()),
            ],
        ),
    ]
