# Generated by Django 5.2.17 on 2026-09-02 16:08

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.BigIntegerField(blank=True, db_index=True, null=True, unique=True, verbose_name='Telegram ID'),
        ),
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=64, verbose_name='Telegram username'),
        ),
        migrations.CreateModel(
            name='TelegramLoginRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(db_index=True, max_length=48, unique=True, verbose_name='Token')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('used', 'Ishlatilgan')], default='pending', max_length=20, verbose_name='Holat')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='Ism')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='Familiya')),
                ('username', models.CharField(blank=True, max_length=64, verbose_name='Username')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='Telefon')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Tasdiqlangan')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='login_requests', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "Telegram kirish so'rovi",
                'verbose_name_plural': "Telegram kirish so'rovlari",
                'ordering': ['-created_at'],
            },
        ),
    ]
