# Generated by Django 5.2.17 on 2026-09-02 16:46

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_telegram_id_user_telegram_username_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramAuthCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=8, unique=True, verbose_name='Kod')),
                ('telegram_id', models.BigIntegerField(verbose_name='Telegram ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Ishlatilgan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='auth_codes', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Telegram kod',
                'verbose_name_plural': 'Telegram kodlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.DeleteModel(
            name='TelegramLoginRequest',
        ),
    ]
