# Generated by Django 5.2.17 on 2026-09-08 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_telegramauthcode_delete_telegramloginrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('yosh', 'Yosh'), ('entrepreneur', 'Tadbirkor'), ('startupper', 'Startupper'), ('organization', 'Tashkilot'), ('admin', 'Administrator')], default='entrepreneur', max_length=20, verbose_name='Rol'),
        ),
    ]
