# Generated by Django 5.2.17 on 2026-09-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_user_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='age',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Yoshi'),
        ),
        migrations.AddField(
            model_name='user',
            name='study_location',
            field=models.CharField(blank=True, choices=[('uz', "O'zbekistonda"), ('abroad', 'Chet elda')], max_length=10, verbose_name="Qayerda ta'lim oladi"),
        ),
    ]
