# Generated by Django 5.2.17 on 2026-09-16 19:39

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_rol_tanlamaganlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Broadcast',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, verbose_name='Matn')),
                ('kind', models.CharField(choices=[('text', 'Matn'), ('photo', 'Rasm'), ('video', 'Video'), ('document', 'Fayl')], default='text', max_length=20, verbose_name='Turi')),
                ('file_id', models.CharField(blank=True, max_length=300, verbose_name='Telegram fayl id')),
                ('buttons', models.JSONField(blank=True, default=list, verbose_name='Tugmalar')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Jami qabul qiluvchi')),
                ('sent', models.PositiveIntegerField(default=0, verbose_name='Yetkazildi')),
                ('failed', models.PositiveIntegerField(default=0, verbose_name='Yetmadi')),
                ('blocked', models.PositiveIntegerField(default=0, verbose_name='Botni bloklaganlar')),
                ('created_by', models.BigIntegerField(blank=True, null=True, verbose_name='Yuborgan admin')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Boshlangan')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugagan')),
            ],
            options={
                'verbose_name': 'Reklama',
                'verbose_name_plural': 'Reklamalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RequiredChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='Chat ID')),
                ('username', models.CharField(blank=True, max_length=64, verbose_name='Username (@ siz)')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('invite_link', models.CharField(blank=True, max_length=300, verbose_name='Havola')),
                ('is_active', models.BooleanField(default=True, verbose_name='Majburiy')),
                ('added_by', models.BigIntegerField(blank=True, null=True, verbose_name="Qo'shgan admin")),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Qo'shilgan")),
            ],
            options={
                'verbose_name': 'Majburiy kanal',
                'verbose_name_plural': 'Majburiy kanallar',
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='ChannelJoin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(db_index=True, verbose_name='Telegram ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Qo'shilgan")),
                ('channel', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='joins', to='accounts.requiredchannel', verbose_name='Kanal')),
            ],
            options={
                'verbose_name': "Kanalga qo'shilish",
                'verbose_name_plural': "Kanalga qo'shilishlar",
                'ordering': ['-created_at'],
                'unique_together': {('channel', 'telegram_id')},
            },
        ),
    ]
