# Generated by Django 5.2.17 on 2026-09-17 17:31

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_bot_kanallar_reklama'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('auto_post', models.BooleanField(default=False, verbose_name='Yangiliklar botga yuborilsin')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name="O'zgartirilgan")),
            ],
            options={
                'verbose_name': 'Bot sozlamasi',
                'verbose_name_plural': 'Bot sozlamalari',
            },
        ),
        migrations.CreateModel(
            name='BotPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('news', 'Yangilik'), ('announcement', "E'lon"), ('startup', 'Startap'), ('business', 'Tadbirkor'), ('peer', 'Chet eldagi tengdosh')], max_length=20, verbose_name='Turi')),
                ('object_id', models.PositiveIntegerField(verbose_name='Yozuv raqami')),
                ('title', models.CharField(max_length=250, verbose_name='Sarlavha')),
                ('excerpt', models.TextField(blank=True, verbose_name='Boshlanishi')),
                ('image_url', models.CharField(blank=True, max_length=400, verbose_name='Rasm')),
                ('link', models.CharField(max_length=400, verbose_name='Havola')),
                ('status', models.CharField(choices=[('pending', 'Navbatda'), ('sent', 'Yuborilgan'), ('failed', 'Xato')], default='pending', max_length=20, verbose_name='Holat')),
                ('total', models.PositiveIntegerField(default=0, verbose_name='Qabul qiluvchi')),
                ('sent', models.PositiveIntegerField(default=0, verbose_name='Yetkazildi')),
                ('failed', models.PositiveIntegerField(default=0, verbose_name='Yetmadi')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Qo'shilgan")),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Yuborilgan')),
            ],
            options={
                'verbose_name': 'Botga yuboriladigan xabar',
                'verbose_name_plural': 'Botga yuboriladigan xabarlar',
                'ordering': ['-created_at'],
                'unique_together': {('kind', 'object_id')},
            },
        ),
    ]
