# Generated by Django 5.2.10 on 2026-09-26 07:23

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_bot_yangiliklari'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=40, unique=True, verbose_name='Havola kaliti')),
                ('ticket', models.CharField(max_length=64, unique=True, verbose_name='Brauzer kaliti')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Yaratilgan')),
                ('opened_at', models.DateTimeField(blank=True, null=True, verbose_name='Botda ochilgan')),
                ('linked_at', models.DateTimeField(blank=True, null=True, verbose_name='Ulangan')),
                ('claimed_at', models.DateTimeField(blank=True, null=True, verbose_name='Saytga kirilgan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_links', to=settings.AUTH_USER_MODEL, verbose_name='Hisob')),
            ],
            options={
                'verbose_name': 'Telegram ulash',
                'verbose_name_plural': 'Telegram ulashlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
