# Generated by Django 5.2.17 on 2026-09-30 06:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_tashkilot_telegram'),
    ]

    operations = [
        migrations.CreateModel(
            name='BotMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(verbose_name='Telegram ID')),
                ('text', models.TextField(verbose_name='Matn (HTML)')),
                ('buttons', models.JSONField(blank=True, default=list, verbose_name='Tugmalar')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name="Qo'shilgan")),
                ('taken_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='Bot olgan')),
                ('delivered', models.BooleanField(blank=True, null=True, verbose_name='Yetkazildi')),
                ('error', models.CharField(blank=True, max_length=200, verbose_name='Xato')),
            ],
            options={
                'verbose_name': 'Shaxsiy bot xabari',
                'verbose_name_plural': 'Shaxsiy bot xabarlari',
                'ordering': ['id'],
            },
        ),
    ]
