# Generated by Django 5.2.10 on 2026-10-07 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_shaxsiy_bot_xabarlari'),
    ]

    operations = [
        migrations.AlterField(
            model_name='botpost',
            name='kind',
            field=models.CharField(choices=[('news', 'Yangilik'), ('announcement', "E'lon"), ('startup', 'Startap'), ('business', 'Tadbirkor'), ('peer', 'Chet eldagi tengdosh'), ('poll', "So'rovnoma")], max_length=20, verbose_name='Turi'),
        ),
    ]
