# Generated by Django 5.2.10 on 2026-10-10 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_sorovnomalar'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='education_place',
            field=models.CharField(blank=True, max_length=200, verbose_name="Ta'lim muassasasi"),
        ),
        migrations.AddField(
            model_name='user',
            name='social_status',
            field=models.CharField(blank=True, choices=[('student', 'Talaba'), ('unemployed', 'Ishsiz'), ('employed', 'Ishlaydi'), ('school', "Maktab o'quvchisi")], db_index=True, max_length=12, verbose_name='Ijtimoiy holati'),
        ),
    ]
