# Generated by Django 5.2.17 on 2026-08-30 17:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('name', models.CharField(max_length=200, verbose_name='Tashkilot nomi')),
                ('sphere', models.CharField(choices=[('davlat', 'Davlat boshqaruvi'), ('qishloq_xojaligi', "Qishloq xo'jaligi"), ('tibbiyot', 'Tibbiyot'), ('talim', "Ta'lim"), ('logistika', 'Logistika'), ('ishlab_chiqarish', 'Ishlab chiqarish'), ('savdo', 'Savdo'), ('xizmat', "Xizmat ko'rsatish"), ('it', 'IT'), ('boshqa', 'Boshqa')], max_length=30, verbose_name='Faoliyat sohasi')),
                ('contact_person', models.CharField(max_length=150, verbose_name='Aloqa shaxsi (F.I.O)')),
                ('phone', models.CharField(max_length=25, verbose_name='Telefon raqami')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('region', models.CharField(blank=True, choices=[('toshkent_shahri', 'Toshkent shahri'), ('toshkent', 'Toshkent viloyati'), ('samarqand', 'Samarqand viloyati'), ('buxoro', 'Buxoro viloyati'), ('navoiy', 'Navoiy viloyati'), ('qashqadaryo', 'Qashqadaryo viloyati'), ('surxondaryo', 'Surxondaryo viloyati'), ('fargona', "Farg'ona viloyati"), ('andijon', 'Andijon viloyati'), ('namangan', 'Namangan viloyati'), ('xorazm', 'Xorazm viloyati'), ('sirdaryo', 'Sirdaryo viloyati'), ('jizzax', 'Jizzax viloyati'), ('qoraqalpogiston', "Qoraqalpog'iston Respublikasi")], max_length=30, verbose_name='Viloyat')),
                ('employees', models.PositiveIntegerField(blank=True, null=True, verbose_name='Xodimlar soni')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='organizations', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Tashkilot',
                'verbose_name_plural': 'Tashkilotlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('category', models.CharField(choices=[('bottlenecks', "Jarayonlardagi to'siqlar"), ('human', 'Inson omili'), ('communication', 'Muloqot va axborot oqimi'), ('technology', 'Texnologiya va avtomatlashtirish'), ('customers', 'Mijozlar fikri'), ('finance', 'Moliya va xarajatlar'), ('management', 'Boshqaruv va nazorat'), ('strategy', 'Strategiya va ijro xatoligi'), ('competition', 'Tashqi xavflar va raqobat'), ('main', 'Asosiy muammo')], max_length=20, verbose_name='Kategoriya')),
                ('description', models.TextField(verbose_name='Muammo tavsifi')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('review', "Ko'rib chiqilmoqda"), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('done', 'Bajarilgan')], default='pending', max_length=20, verbose_name='Holat')),
                ('is_published', models.BooleanField(default=True, verbose_name="Yoshlarga ko'rinsin")),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='problems', to='initiatives.organization', verbose_name='Tashkilot')),
            ],
            options={
                'verbose_name': 'Muammo',
                'verbose_name_plural': 'Muammolar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Solution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('author_name', models.CharField(max_length=150, verbose_name='F.I.O.')),
                ('author_phone', models.CharField(blank=True, max_length=25, verbose_name='Telefon')),
                ('author_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('title', models.CharField(max_length=200, verbose_name='Yechim nomi')),
                ('description', models.TextField(verbose_name='Yechim tavsifi')),
                ('technologies', models.CharField(blank=True, max_length=300, verbose_name='Texnologiyalar va vositalar')),
                ('expected_result', models.TextField(blank=True, verbose_name='Kutilayotgan natija')),
                ('attachment', models.FileField(blank=True, upload_to='solutions/%Y/%m/', verbose_name="Qo'shimcha fayl")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('review', "Ko'rib chiqilmoqda"), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('done', 'Bajarilgan')], default='pending', max_length=20, verbose_name='Holat')),
                ('admin_note', models.TextField(blank=True, verbose_name='Admin izohi')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='solutions', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='initiatives.problem', verbose_name='Muammo')),
            ],
            options={
                'verbose_name': 'Yechim',
                'verbose_name_plural': 'Yechimlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
