# Generated by Django 5.2.17 on 2026-09-01 17:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Initiative',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('direction', models.CharField(choices=[('eco', 'Ekologiya'), ('fintech', 'Fintex'), ('ai', "Sun'iy intellekt"), ('edu', "Ta'lim"), ('social', 'Ijtimoiy soha'), ('agro', 'Agrotexnologiya'), ('energy', 'Energetika'), ('industry', 'Sanoat'), ('startup', 'Startap'), ('creative', 'Ijodiy sanoat'), ('culture', 'Madaniyat'), ('smartcity', 'Aqlli shahar'), ('science', 'Fan'), ('water', 'Suv texnologiyalari')], db_index=True, default='eco', max_length=20, verbose_name="Yo'nalish")),
                ('kind', models.CharField(choices=[('problem', 'Muammo'), ('idea', "G'oya"), ('proposal', 'Taklif'), ('startup', "StartUp g'oyasi")], default='idea', max_length=20, verbose_name='Turi')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('summary', models.CharField(blank=True, max_length=300, verbose_name='Qisqa mazmun')),
                ('description', models.TextField(verbose_name='Batafsil tavsif')),
                ('expected_result', models.TextField(blank=True, verbose_name='Kutilayotgan natija')),
                ('author_name', models.CharField(max_length=150, verbose_name='F.I.O.')),
                ('author_phone', models.CharField(blank=True, max_length=25, verbose_name='Telefon')),
                ('author_email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('region', models.CharField(blank=True, choices=[('toshkent_shahri', 'Toshkent shahri'), ('toshkent', 'Toshkent viloyati'), ('samarqand', 'Samarqand viloyati'), ('buxoro', 'Buxoro viloyati'), ('navoiy', 'Navoiy viloyati'), ('qashqadaryo', 'Qashqadaryo viloyati'), ('surxondaryo', 'Surxondaryo viloyati'), ('fargona', "Farg'ona viloyati"), ('andijon', 'Andijon viloyati'), ('namangan', 'Namangan viloyati'), ('xorazm', 'Xorazm viloyati'), ('sirdaryo', 'Sirdaryo viloyati'), ('jizzax', 'Jizzax viloyati'), ('qoraqalpogiston', "Qoraqalpog'iston Respublikasi")], max_length=30, verbose_name='Viloyat')),
                ('vote_count', models.PositiveIntegerField(db_index=True, default=0, verbose_name='Ovozlar')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('review', "Ko'rib chiqilmoqda"), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('done', 'Bajarilgan')], default='approved', max_length=20, verbose_name='Holat')),
                ('is_published', models.BooleanField(default=True, verbose_name="Ko'rinsin")),
                ('admin_note', models.TextField(blank=True, verbose_name='Admin izohi')),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiatives', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
            ],
            options={
                'verbose_name': 'Tashabbus',
                'verbose_name_plural': 'Tashabbuslar',
                'ordering': ['-vote_count', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InitiativeVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('session_key', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Sessiya kaliti')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='initiatives.initiative', verbose_name='Tashabbus')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='initiative_votes', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Ovoz',
                'verbose_name_plural': 'Ovozlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='initiative',
            index=models.Index(fields=['direction', '-vote_count'], name='initiatives_directi_c6fa1e_idx'),
        ),
        migrations.AddConstraint(
            model_name='initiativevote',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', False)), fields=('initiative', 'user'), name='uniq_vote_per_user'),
        ),
        migrations.AddConstraint(
            model_name='initiativevote',
            constraint=models.UniqueConstraint(condition=models.Q(('user__isnull', True)), fields=('initiative', 'session_key'), name='uniq_vote_per_session'),
        ),
    ]
