# Generated by Django 5.2.17 on 2026-09-02 13:20

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0002_initiative_initiativevote_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InitiativeComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('author_name', models.CharField(max_length=150, verbose_name='F.I.O.')),
                ('text', models.TextField(verbose_name='Taklif matni')),
                ('is_published', models.BooleanField(default=True, verbose_name="Ko'rinsin")),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='initiative_comments', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
                ('initiative', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='initiatives.initiative', verbose_name='Tashabbus')),
            ],
            options={
                'verbose_name': 'Taklif (izoh)',
                'verbose_name_plural': 'Takliflar (izohlar)',
                'ordering': ['-created_at'],
            },
        ),
    ]
