# Generated by Django 5.2.17 on 2026-09-08 18:03

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('initiatives', '0003_initiativecomment'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SolutionLike',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
            ],
            options={
                'verbose_name': 'Taklif layki',
                'verbose_name_plural': 'Taklif layklari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterModelOptions(
            name='solution',
            options={'ordering': ['-like_count', '-created_at'], 'verbose_name': 'Yechim', 'verbose_name_plural': 'Yechimlar'},
        ),
        migrations.AddField(
            model_name='solution',
            name='like_count',
            field=models.PositiveIntegerField(db_index=True, default=0, verbose_name='Layklar'),
        ),
        migrations.AddIndex(
            model_name='solution',
            index=models.Index(fields=['problem', '-like_count'], name='initiatives_problem_fa5576_idx'),
        ),
        migrations.AddField(
            model_name='solutionlike',
            name='solution',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='likes', to='initiatives.solution', verbose_name='Taklif'),
        ),
        migrations.AddField(
            model_name='solutionlike',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solution_likes', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi'),
        ),
        migrations.AddConstraint(
            model_name='solutionlike',
            constraint=models.UniqueConstraint(fields=('solution', 'user'), name='uniq_like_per_user'),
        ),
    ]
