# Generated by Django 5.2.17 on 2026-08-30 17:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Announcement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('title', models.CharField(max_length=250, verbose_name='Sarlavha')),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True, verbose_name='Havola')),
                ('type', models.CharField(choices=[('grant', 'Grant'), ('kredit', 'Kredit'), ('tanlov', 'Tanlov'), ('seminar', 'Seminar'), ('trening', 'Trening'), ('vakansiya', 'Vakansiya'), ('davlat_dasturi', 'Davlat dasturi')], max_length=20, verbose_name='Turi')),
                ('body', models.TextField(verbose_name='Matn')),
                ('file', models.FileField(blank=True, upload_to='announcements/%Y/%m/', verbose_name='Fayl')),
                ('posted_at', models.DateField(default=django.utils.timezone.localdate, verbose_name='Joylangan sana')),
                ('deadline', models.DateField(blank=True, null=True, verbose_name='Muddat')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': "E'lon",
                'verbose_name_plural': "E'lonlar",
                'ordering': ['-posted_at'],
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('title', models.CharField(max_length=250, verbose_name='Nomi')),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True, verbose_name='Havola')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('starts_at', models.DateTimeField(verbose_name='Boshlanish vaqti')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Tugash vaqti')),
                ('location', models.CharField(max_length=250, verbose_name='Manzil')),
                ('region', models.CharField(blank=True, choices=[('toshkent_shahri', 'Toshkent shahri'), ('toshkent', 'Toshkent viloyati'), ('samarqand', 'Samarqand viloyati'), ('buxoro', 'Buxoro viloyati'), ('navoiy', 'Navoiy viloyati'), ('qashqadaryo', 'Qashqadaryo viloyati'), ('surxondaryo', 'Surxondaryo viloyati'), ('fargona', "Farg'ona viloyati"), ('andijon', 'Andijon viloyati'), ('namangan', 'Namangan viloyati'), ('xorazm', 'Xorazm viloyati'), ('sirdaryo', 'Sirdaryo viloyati'), ('jizzax', 'Jizzax viloyati'), ('qoraqalpogiston', "Qoraqalpog'iston Respublikasi")], max_length=30, verbose_name='Viloyat')),
                ('capacity', models.PositiveIntegerField(default=100, verbose_name='Ishtirokchilar limiti')),
                ('image', models.ImageField(blank=True, upload_to='events/%Y/%m/', verbose_name='Rasm')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chop etilgan')),
            ],
            options={
                'verbose_name': 'Tadbir',
                'verbose_name_plural': 'Tadbirlar',
                'ordering': ['starts_at'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('title', models.CharField(max_length=250, verbose_name='Sarlavha')),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True, verbose_name='Havola')),
                ('category', models.CharField(choices=[('grant', 'Grant'), ('forum', 'Forum'), ('trening', 'Trening'), ('kredit', 'Kredit'), ('eksport', 'Eksport'), ('tanlov', 'Tanlov')], max_length=20, verbose_name='Kategoriya')),
                ('excerpt', models.TextField(max_length=500, verbose_name='Qisqacha')),
                ('body', models.TextField(verbose_name='Matn')),
                ('image', models.ImageField(blank=True, upload_to='news/%Y/%m/', verbose_name='Rasm')),
                ('author_name', models.CharField(blank=True, max_length=150, verbose_name='Muallif ismi')),
                ('published_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Chop etilgan sana')),
                ('is_published', models.BooleanField(default=True, verbose_name='Chop etilgan')),
                ('is_featured', models.BooleanField(default=False, verbose_name='Asosiy yangilik')),
                ('views', models.PositiveIntegerField(default=0, verbose_name="Ko'rishlar")),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='news', to=settings.AUTH_USER_MODEL, verbose_name='Muallif')),
            ],
            options={
                'verbose_name': 'Yangilik',
                'verbose_name_plural': 'Yangiliklar',
                'ordering': ['-published_at'],
            },
        ),
        migrations.CreateModel(
            name='EventRegistration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('note', models.TextField(blank=True, verbose_name='Izoh')),
                ('is_cancelled', models.BooleanField(default=False, verbose_name='Bekor qilingan')),
                ('attended', models.BooleanField(default=False, verbose_name='Qatnashgan')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='registrations', to='content.event', verbose_name='Tadbir')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='event_registrations', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Tadbirga yozilish',
                'verbose_name_plural': 'Tadbirga yozilishlar',
                'ordering': ['-created_at'],
                'unique_together': {('event', 'user')},
            },
        ),
    ]
