# Generated by Django 5.2.17 on 2026-09-16 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='announcement',
            index=models.Index(fields=['is_active', '-posted_at'], name='content_ann_is_acti_ecf003_idx'),
        ),
        migrations.AddIndex(
            model_name='event',
            index=models.Index(fields=['is_published', 'starts_at'], name='content_eve_is_publ_b78861_idx'),
        ),
        migrations.AddIndex(
            model_name='news',
            index=models.Index(fields=['is_published', '-published_at'], name='content_new_is_publ_17b567_idx'),
        ),
    ]
