# Generated by Django 5.2.10 on 2026-09-26 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_tezlik_indekslari'),
    ]

    operations = [
        migrations.AddField(
            model_name='announcement',
            name='apply_url',
            field=models.URLField(blank=True, max_length=500, verbose_name='Murojaat havolasi'),
        ),
        migrations.AddField(
            model_name='announcement',
            name='image',
            field=models.ImageField(blank=True, upload_to='announcements/images/%Y/%m/', verbose_name='Rasm'),
        ),
    ]
