# Generated by Django 5.2.17 on 2026-10-07 08:13

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_elon_rasm_havola'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Poll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('title', models.CharField(max_length=250, verbose_name='Sarlavha')),
                ('slug', models.SlugField(blank=True, max_length=270, unique=True, verbose_name='Havola')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('image', models.ImageField(blank=True, upload_to='polls/%Y/%m/', verbose_name='Muqova')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Ovoz berish tugashi')),
                ('is_active', models.BooleanField(default=True, verbose_name="Saytda ko'rinadi")),
                ('show_results', models.BooleanField(default=True, help_text="O'chiq bo'lsa ovozlar soni faqat panelda ko'rinadi", verbose_name='Natijalar ochiq')),
                ('podium_min_votes', models.PositiveIntegerField(default=1000, verbose_name='Peshqadamlik uchun eng kam ovoz')),
            ],
            options={
                'verbose_name': "So'rovnoma",
                'verbose_name_plural': "So'rovnomalar",
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['is_active', '-created_at'], name='content_pol_is_acti_6ba988_idx')],
            },
        ),
        migrations.CreateModel(
            name='PollOption',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('name', models.CharField(max_length=150, verbose_name='F.I.O. / nomi')),
                ('mahalla', models.CharField(blank=True, max_length=150, verbose_name='Mahalla')),
                ('district', models.CharField(blank=True, choices=[('samarqand_shahri', 'Samarqand shahri'), ('kattaqorgon_shahri', "Kattaqo'rg'on shahri"), ('bulungur', "Bulung'ur tumani"), ('jomboy', 'Jomboy tumani'), ('ishtixon', 'Ishtixon tumani'), ('kattaqorgon', "Kattaqo'rg'on tumani"), ('qoshrabot', "Qo'shrabot tumani"), ('narpay', 'Narpay tumani'), ('nurobod', 'Nurobod tumani'), ('oqdaryo', 'Oqdaryo tumani'), ('pastdargom', "Pastdarg'om tumani"), ('paxtachi', 'Paxtachi tumani'), ('payariq', 'Payariq tumani'), ('samarqand_tumani', 'Samarqand tumani'), ('toyloq', 'Toyloq tumani'), ('urgut', 'Urgut tumani')], max_length=30, verbose_name='Tuman / shahar')),
                ('note', models.CharField(blank=True, max_length=300, verbose_name="Qisqa ma'lumot")),
                ('photo', models.ImageField(blank=True, upload_to='polls/options/%Y/%m/', verbose_name='Rasm')),
                ('order', models.PositiveSmallIntegerField(default=0, verbose_name='Tartib')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='options', to='content.poll', verbose_name="So'rovnoma")),
            ],
            options={
                'verbose_name': 'Nomzod',
                'verbose_name_plural': 'Nomzodlar',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PollVote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('option', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='content.polloption', verbose_name='Nomzod')),
                ('poll', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='votes', to='content.poll', verbose_name="So'rovnoma")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='poll_votes', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': "So'rovnoma ovozi",
                'verbose_name_plural': "So'rovnoma ovozlari",
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('poll', 'user'), name='uniq_poll_vote_per_user')],
            },
        ),
    ]
