# Generated by Django 5.2.17 on 2026-08-30 17:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appeal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('subject', models.CharField(max_length=200, verbose_name='Mavzu')),
                ('category', models.CharField(choices=[('moliya', "Moliyaviy qo'llab-quvvatlash"), ('huquqiy', 'Huquqiy yordam'), ('talim', "Ta'lim va trening"), ('eksport', 'Eksport masalalari'), ('soliq', 'Soliq masalalari'), ('hamkorlik', 'Hamkorlik'), ('boshqa', 'Boshqa')], default='boshqa', max_length=20, verbose_name='Kategoriya')),
                ('message', models.TextField(verbose_name='Murojaat matni')),
                ('attachment', models.FileField(blank=True, upload_to='appeals/%Y/%m/', verbose_name='Fayl')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('review', "Ko'rib chiqilmoqda"), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('done', 'Bajarilgan')], default='pending', max_length=20, verbose_name='Holat')),
                ('response', models.TextField(blank=True, verbose_name='Javob')),
                ('responded_at', models.DateTimeField(blank=True, null=True, verbose_name='Javob berilgan vaqt')),
                ('responded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='answered_appeals', to=settings.AUTH_USER_MODEL, verbose_name='Javob bergan')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='appeals', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Murojaat',
                'verbose_name_plural': 'Murojaatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('title', models.CharField(max_length=200, verbose_name='Sarlavha')),
                ('message', models.TextField(blank=True, verbose_name='Matn')),
                ('type', models.CharField(choices=[('info', "Ma'lumot"), ('success', 'Muvaffaqiyat'), ('warning', 'Ogohlantirish'), ('event', 'Tadbir')], default='info', max_length=20, verbose_name='Turi')),
                ('link', models.CharField(blank=True, max_length=300, verbose_name='Havola')),
                ('is_read', models.BooleanField(default=False, verbose_name="O'qilgan")),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Bildirishnoma',
                'verbose_name_plural': 'Bildirishnomalar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('title', models.CharField(max_length=200, verbose_name='Taklif nomi')),
                ('description', models.TextField(verbose_name='Tavsif')),
                ('expected_benefit', models.TextField(blank=True, verbose_name='Kutilayotgan foyda')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('review', "Ko'rib chiqilmoqda"), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('done', 'Bajarilgan')], default='pending', max_length=20, verbose_name='Holat')),
                ('response', models.TextField(blank=True, verbose_name='Javob')),
                ('votes', models.PositiveIntegerField(default=0, verbose_name='Ovozlar')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Taklif',
                'verbose_name_plural': 'Takliflar',
                'ordering': ['-created_at'],
            },
        ),
    ]
