# Generated by Django 5.2.17 on 2026-08-30 17:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSetting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('site_name', models.CharField(default='sam-yosh tadbirkor.uz', max_length=120, verbose_name='Sayt nomi')),
                ('tagline', models.TextField(default="O'zbekiston yosh tadbirkorlarini birlashtiruvchi, qo'llab-quvvatlovchi va rivojlantirishga xizmat qiluvchi yagona axborot platformasi.", verbose_name='Qisqa tavsif')),
                ('address', models.CharField(blank=True, max_length=255, verbose_name='Manzil')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('work_hours', models.CharField(blank=True, max_length=120, verbose_name='Ish vaqti')),
                ('telegram_url', models.URLField(blank=True, verbose_name='Telegram')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
            ],
            options={
                'verbose_name': 'Sayt sozlamasi',
                'verbose_name_plural': 'Sayt sozlamalari',
            },
        ),
    ]
