# Generated by Django 5.2.17 on 2026-08-31 07:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('full_name', models.CharField(max_length=150, verbose_name='F.I.O.')),
                ('position', models.CharField(max_length=150, verbose_name="Lavozim / yo'nalish")),
                ('role', models.CharField(choices=[('chairman', 'Kengash Raisi'), ('secretary', 'Kengash Kotibi'), ('member', "Kengash A'zosi")], default='member', max_length=20, verbose_name='Toifa')),
                ('bio', models.TextField(blank=True, verbose_name="Qisqacha ma'lumot")),
                ('photo', models.ImageField(blank=True, upload_to='leaders/', verbose_name='Rasm')),
                ('region', models.CharField(blank=True, choices=[('toshkent_shahri', 'Toshkent shahri'), ('toshkent', 'Toshkent viloyati'), ('samarqand', 'Samarqand viloyati'), ('buxoro', 'Buxoro viloyati'), ('navoiy', 'Navoiy viloyati'), ('qashqadaryo', 'Qashqadaryo viloyati'), ('surxondaryo', 'Surxondaryo viloyati'), ('fargona', "Farg'ona viloyati"), ('andijon', 'Andijon viloyati'), ('namangan', 'Namangan viloyati'), ('xorazm', 'Xorazm viloyati'), ('sirdaryo', 'Sirdaryo viloyati'), ('jizzax', 'Jizzax viloyati'), ('qoraqalpogiston', "Qoraqalpog'iston Respublikasi")], max_length=30, verbose_name='Hudud')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': "Rahbar / a'zo",
                'verbose_name_plural': "Rahbariyat va a'zolar",
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('text', models.CharField(max_length=300, verbose_name='Vazifa')),
                ('order', models.PositiveIntegerField(default=0, verbose_name='Tartib')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
            ],
            options={
                'verbose_name': 'Kengash vazifasi',
                'verbose_name_plural': 'Kengash vazifalari',
                'ordering': ['order', 'pk'],
            },
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='charter_file',
            field=models.FileField(blank=True, upload_to='documents/', verbose_name='Nizom fayli'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='mission',
            field=models.TextField(default="O'zbekiston yosh tadbirkorlarini qo'llab-quvvatlash, ularning salohiyatini oshirish va biznes muhitini yaxshilash.", verbose_name='Maqsad'),
        ),
        migrations.AddField(
            model_name='sitesetting',
            name='vision',
            field=models.TextField(default="Har bir yosh tadbirkor o'z g'oyasini muvaffaqiyatli biznesga aylantira oladigan muhitni yaratish.", verbose_name='Viziya'),
        ),
    ]
