# Generated by Django 5.2.10 on 2026-09-26 13:23

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_tagline_yoshlar'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServerError',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(max_length=40, unique=True, verbose_name='Belgi')),
                ('title', models.CharField(max_length=300, verbose_name='Xato')),
                ('location', models.CharField(blank=True, max_length=300, verbose_name='Joyi')),
                ('method', models.CharField(blank=True, max_length=10, verbose_name='Usul')),
                ('path', models.CharField(blank=True, max_length=500, verbose_name='Manzil')),
                ('traceback', models.TextField(blank=True, verbose_name='Traceback')),
                ('count', models.PositiveIntegerField(default=1, verbose_name='Necha marta')),
                ('first_seen', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Birinchi marta')),
                ('last_seen', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Oxirgi marta')),
                ('notified_at', models.DateTimeField(blank=True, null=True, verbose_name='Adminlarga yuborilgan')),
            ],
            options={
                'verbose_name': 'Server xatosi',
                'verbose_name_plural': 'Server xatolari',
                'ordering': ['-last_seen'],
            },
        ),
    ]
