# Generated by Django 5.2.17 on 2026-08-30 17:38

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('name', models.CharField(max_length=200, verbose_name='Korxona nomi')),
                ('sphere', models.CharField(choices=[('it', 'IT va raqamlashtirish'), ('qishloq_xojaligi', "Qishloq xo'jaligi"), ('ishlab_chiqarish', 'Ishlab chiqarish'), ('xizmat', "Xizmat ko'rsatish"), ('savdo', 'Savdo va eksport'), ('talim', "Ta'lim va innovatsiya"), ('turizm', 'Turizm'), ('sogliqni_saqlash', "Sog'liqni saqlash"), ('qurilish', 'Qurilish'), ('oziq_ovqat', 'Oziq-ovqat'), ('logistika', 'Logistika'), ('boshqa', 'Boshqa')], max_length=30, verbose_name='Faoliyat sohasi')),
                ('stir', models.CharField(blank=True, max_length=20, verbose_name='STIR (INN)')),
                ('founded_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Tashkil topgan yili')),
                ('employees', models.PositiveIntegerField(default=1, verbose_name='Xodimlar soni')),
                ('region', models.CharField(blank=True, choices=[('toshkent_shahri', 'Toshkent shahri'), ('toshkent', 'Toshkent viloyati'), ('samarqand', 'Samarqand viloyati'), ('buxoro', 'Buxoro viloyati'), ('navoiy', 'Navoiy viloyati'), ('qashqadaryo', 'Qashqadaryo viloyati'), ('surxondaryo', 'Surxondaryo viloyati'), ('fargona', "Farg'ona viloyati"), ('andijon', 'Andijon viloyati'), ('namangan', 'Namangan viloyati'), ('xorazm', 'Xorazm viloyati'), ('sirdaryo', 'Sirdaryo viloyati'), ('jizzax', 'Jizzax viloyati'), ('qoraqalpogiston', "Qoraqalpog'iston Respublikasi")], max_length=30, verbose_name='Viloyat')),
                ('district', models.CharField(blank=True, max_length=100, verbose_name='Tuman / shahar')),
                ('address', models.CharField(blank=True, max_length=250, verbose_name='Manzil')),
                ('description', models.TextField(blank=True, verbose_name='Biznes haqida')),
                ('logo', models.ImageField(blank=True, upload_to='business/logos/%Y/%m/', verbose_name='Logotip')),
                ('website', models.URLField(blank=True, verbose_name='Veb-sayt')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='Telefon')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='Instagram')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('review', "Ko'rib chiqilmoqda"), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('done', 'Bajarilgan')], default='pending', max_length=20, verbose_name='Holat')),
                ('is_public', models.BooleanField(default=True, verbose_name="Ommaviy ro'yxatda ko'rinsin")),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='business', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Biznes profil',
                'verbose_name_plural': 'Biznes profillar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('title', models.CharField(max_length=200, verbose_name='Nomi')),
                ('type', models.CharField(choices=[('guvohnoma', 'Guvohnoma'), ('litsenziya', 'Litsenziya'), ('shartnoma', 'Shartnoma'), ('hisobot', 'Hisobot'), ('boshqa', 'Boshqa')], default='boshqa', max_length=20, verbose_name='Turi')),
                ('file', models.FileField(upload_to='business/documents/%Y/%m/', verbose_name='Fayl')),
                ('note', models.CharField(blank=True, max_length=250, verbose_name='Izoh')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='business.businessprofile', verbose_name='Biznes')),
            ],
            options={
                'verbose_name': 'Hujjat',
                'verbose_name_plural': 'Hujjatlar',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('image', models.ImageField(upload_to='business/gallery/%Y/%m/', verbose_name='Rasm')),
                ('caption', models.CharField(blank=True, max_length=200, verbose_name='Izoh')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='business.businessprofile', verbose_name='Biznes')),
            ],
            options={
                'verbose_name': 'Galereya rasmi',
                'verbose_name_plural': 'Galereya rasmlari',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('name', models.CharField(max_length=200, verbose_name='Nomi')),
                ('description', models.TextField(blank=True, verbose_name='Tavsif')),
                ('price', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name="Narxi (so'm)")),
                ('unit', models.CharField(blank=True, default='dona', max_length=40, verbose_name="O'lchov birligi")),
                ('image', models.ImageField(blank=True, upload_to='business/products/%Y/%m/', verbose_name='Rasm')),
                ('is_active', models.BooleanField(default=True, verbose_name='Faol')),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='products', to='business.businessprofile', verbose_name='Biznes')),
            ],
            options={
                'verbose_name': 'Mahsulot',
                'verbose_name_plural': 'Mahsulotlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
