# Generated by Django 5.2.17 on 2026-09-16 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='businessprofile',
            index=models.Index(fields=['is_public', 'status', '-created_at'], name='business_bu_is_publ_8a7c1a_idx'),
        ),
    ]
