# Generated by Django 5.2.17 on 2026-09-02 14:28

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Peer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='Yaratilgan')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Yangilangan')),
                ('full_name', models.CharField(max_length=150, verbose_name='F.I.O.')),
                ('photo', models.ImageField(blank=True, upload_to='peers/%Y/%m/', verbose_name='Rasm')),
                ('country', models.CharField(choices=[('usa', 'AQSh'), ('uk', 'Buyuk Britaniya'), ('germany', 'Germaniya'), ('turkey', 'Turkiya'), ('russia', 'Rossiya'), ('korea', 'Janubiy Koreya'), ('japan', 'Yaponiya'), ('china', 'Xitoy'), ('uae', 'BAA'), ('kazakhstan', "Qozog'iston"), ('poland', 'Polsha'), ('italy', 'Italiya'), ('france', 'Fransiya'), ('canada', 'Kanada'), ('malaysia', 'Malayziya'), ('india', 'Hindiston'), ('latvia', 'Latviya'), ('czech', 'Chexiya'), ('other', 'Boshqa davlat')], db_index=True, max_length=20, verbose_name='Davlat')),
                ('city', models.CharField(blank=True, max_length=100, verbose_name='Shahar')),
                ('home_region', models.CharField(blank=True, choices=[('toshkent_shahri', 'Toshkent shahri'), ('toshkent', 'Toshkent viloyati'), ('samarqand', 'Samarqand viloyati'), ('buxoro', 'Buxoro viloyati'), ('navoiy', 'Navoiy viloyati'), ('qashqadaryo', 'Qashqadaryo viloyati'), ('surxondaryo', 'Surxondaryo viloyati'), ('fargona', "Farg'ona viloyati"), ('andijon', 'Andijon viloyati'), ('namangan', 'Namangan viloyati'), ('xorazm', 'Xorazm viloyati'), ('sirdaryo', 'Sirdaryo viloyati'), ('jizzax', 'Jizzax viloyati'), ('qoraqalpogiston', "Qoraqalpog'iston Respublikasi")], max_length=30, verbose_name="O'zbekistondagi hududi")),
                ('purpose', models.CharField(choices=[('study', "O'qiyapman"), ('work', 'Ishlayapman'), ('business', 'Biznes yuritaman'), ('research', 'Ilmiy tadqiqot'), ('internship', 'Amaliyot / stajirovka'), ('other', 'Boshqa')], default='study', max_length=20, verbose_name='U yerda nima qilyapti')),
                ('institution', models.CharField(blank=True, max_length=200, verbose_name='Universitet / kompaniya')),
                ('field', models.CharField(blank=True, max_length=150, verbose_name="Yo'nalish / kasb")),
                ('since_year', models.PositiveIntegerField(blank=True, null=True, verbose_name='Qaysi yildan beri')),
                ('about', models.TextField(verbose_name="O'zi haqida")),
                ('can_help', models.TextField(blank=True, verbose_name='Nimada yordam bera oladi')),
                ('telegram', models.CharField(blank=True, max_length=100, verbose_name='Telegram')),
                ('instagram', models.CharField(blank=True, max_length=100, verbose_name='Instagram')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='Email')),
                ('phone', models.CharField(blank=True, max_length=25, verbose_name='Telefon')),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('review', "Ko'rib chiqilmoqda"), ('approved', 'Tasdiqlangan'), ('rejected', 'Rad etilgan'), ('done', 'Bajarilgan')], default='pending', max_length=20, verbose_name='Holat')),
                ('is_published', models.BooleanField(default=True, verbose_name="Ko'rinsin")),
                ('admin_note', models.TextField(blank=True, verbose_name='Admin izohi')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='peer_profiles', to=settings.AUTH_USER_MODEL, verbose_name='Foydalanuvchi')),
            ],
            options={
                'verbose_name': 'Chet eldagi tengdosh',
                'verbose_name_plural': 'Chet eldagi tengdoshlar',
                'ordering': ['-created_at'],
            },
        ),
    ]
