# Generated by Django 5.2.17 on 2026-09-13 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abroad', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='peer',
            name='achievements',
            field=models.CharField(blank=True, max_length=300, verbose_name='Yutuqlari'),
        ),
        migrations.AddField(
            model_name='peer',
            name='course',
            field=models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Nechanchi kurs'),
        ),
        migrations.AlterField(
            model_name='peer',
            name='about',
            field=models.TextField(blank=True, verbose_name="O'zi haqida"),
        ),
    ]
