# Generated by Django 5.2.17 on 2026-09-16 19:20

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abroad', '0002_yosh_va_talim'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='peer',
            index=models.Index(fields=['is_published', 'status', '-created_at'], name='abroad_peer_is_publ_b4e60d_idx'),
        ),
    ]
